# enumerators for stop service
int32 TO_ZERO_VEL = 1
int32 SOFT_ESTOP = 2
int32 RESUME_SOFT_ESTOP = 3
int32 SLOW_SOFT_ESTOP = 5

int32 command

#
string owner

# only used when change status of a single robot
string serial

# any additional info needed, can be empty
string other

---

bool confirm

int32 state_id

string state_name
