uint8 WAGO_MBUS_IO_HOKUYO_HB1 = 0
uint8 WAGO_MBUS_IO_HOKUYO_HB2 = 1
uint8 WAGO_MBUS_IO_AGV_LOUDSPEAKER = 2
uint8 WAGO_MBUS_IO_AGV_POLE_BAR = 3
uint8 WAGO_MBUS_IO_LEFT_RIGHT_TURN_SIGNALS = 4
uint8 WAGO_MBUS_IO_UNKNOWN = 8

uint8 HOKUYO_HB1_MEAN_AGV_LEFT = 0
uint8 HOKUYO_HB1_MEAN_AGV_REACHED = 1

uint8 AGV_LOUDSPEAKER_IO_OFF = 0
uint8 AGV_LOUDSPEAKER_IO_ON = 1

uint8 AGV_POLE_BAR_NORMAL_DOWN = 0
uint8 AGV_POLE_BAR_NORMAL_IDLE = 1
uint8 AGV_POLE_BAR_WARN_LEVEL_1 = 2
uint8 AGV_POLE_BAR_WARN_LEVEL_2 = 3
uint8 AGV_POLE_BAR_WARN_LEVEL_3 = 4
uint8 AGV_POLE_BAR_URGENT_FAULT = 5

uint8 AGV_TURN_SIGNALS_GO_STRAIGHT = 0
uint8 AGV_TURN_SIGNALS_GO_BACK = 1
uint8 AGV_TURN_SIGNALS_GO_LEFT = 2
uint8 AGV_TURN_SIGNALS_GO_RIGHT = 3




int32 owner_io

int32 state

---

bool confirm


